### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kperreau** [MinaSamir11/react-native-in-app-review#18] opened 2020-12-10 14:23 UTC
Hello, i got this **crash error** on **Android** for some of my users.

**Error:**
`Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference`

**Stack trace:**
`com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1 (AppReviewModule.java:43)`

**It's maybe related to this:**
https://stackoverflow.com/questions/28515049/android-content-context-getpackagename-on-a-null-object-reference

But i'm not a Java developper, so i can't help.

**Comment by MinaSamir11** [comment] 2020-12-11 22:13
what's your react native version ?

**Comment by MinaSamir11** [comment] 2020-12-12 01:18
please check new release version 2.1.5. 
and give me feedback again about your issue, is it solved ?

**Comment by kperreau** [comment] 2020-12-12 02:02
> 
> 
> what's your react native version ?
> and
> Device model and android version of users that crash your app?

**react-native** `0.63.3`.

**Android:** `8`, `9`.

**Devices:** `Galaxy S7 edge`, `P20 lite`, `Redmi Note 8`,  `Galaxy S8`, `Galaxy J5`,  `Redmi Note 7`.

I'll try the new version `2.1.5` and tell you if new crash coming.

**Comment by perrosnk** [comment] 2020-12-29 13:26
Has this issue been solved? @kperreau @MinaSamir11

**Comment by kperreau** [comment] 2020-12-30 18:35
Still an issue.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

android.content.ComponentName.<init> (ComponentName.java:131)
android.content.Intent.<init> (Intent.java:6663)
com.google.android.play.core.review.c.launchReviewFlow (c.java:4)
com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1 (AppReviewModule.java:49)
com.ibits.react_native_in_app_review.-$$Lambda$AppReviewModule$bUmS5pB5E-8STvn0S-VVfLR6ozE.onComplete (-.java:4)
com.google.android.play.core.tasks.a.run (a.java:23)
android.os.Handler.handleCallback (Handler.java:888)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:213)
android.app.ActivityThread.main (ActivityThread.java:8178)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
```

**Package version:** `2.1.5`

**Comment by MinaSamir11** [comment] 2020-12-31 12:45
> Still an issue.
> 
> ```
> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
> 
> android.content.ComponentName.<init> (ComponentName.java:131)
> android.content.Intent.<init> (Intent.java:6663)
> com.google.android.play.core.review.c.launchReviewFlow (c.java:4)
> com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1 (AppReviewModule.java:49)
> com.ibits.react_native_in_app_review.-$$Lambda$AppReviewModule$bUmS5pB5E-8STvn0S-VVfLR6ozE.onComplete (-.java:4)
> com.google.android.play.core.tasks.a.run (a.java:23)
> android.os.Handler.handleCallback (Handler.java:888)
> android.os.Handler.dispatchMessage (Handler.java:100)
> android.os.Looper.loop (Looper.java:213)
> android.app.ActivityThread.main (ActivityThread.java:8178)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
> ```
> 
> **Package version:** `2.1.5`

"android.content.Context.getPackageName"
this line of code founded in 2.1.4, but it has been removed in version 2.1.5, maybe you don't clear the cache of npm, try to run the command `npm start -- --reset-cache`. to rm old version of package.

**Comment by MinaSamir11** [comment] 2020-12-31 12:48
> Has this issue been solved? @kperreau @MinaSamir11

if not resolved with you in version 2.1.5, try to use the new version 2.1.6. 
and make sure to clear the cache of the packager with this command `npm start -- --reset-cache`

**Comment by perrosnk** [comment] 2021-01-11 22:29
I am getting a similar issue with v.2.1.6:
`Fatal Exception: com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service`

`
Caused by com.google.android.play.core.internal.aq: Failed to bind to the service.
       at com.google.android.play.core.internal.ap.a(:76)
       at com.google.android.play.core.internal.ai.a(:4)
       at com.google.android.play.core.internal.ag.run()
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
`

Could this help?
https://github.com/Skyost/RateMyApp/issues/72#issuecomment-687873739

**Comment by perrosnk** [comment] 2021-01-12 14:46
Some more info:

`
Fatal Exception: com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service.
       at com.google.android.play.core.tasks.m.getResult()
       at com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1$AppReviewModule(AppReviewModule.java:62)
       at com.ibits.react_native_in_app_review.-$$Lambda$AppReviewModule$[SOME_RANDOM_STRING].onComplete(lambda)
       at com.google.android.play.core.tasks.a.run()
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6215)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

note: I have removed SOME_RANDOM_STRING because I don't know what this weird string might be

**Comment by MinaSamir11** [comment] 2021-01-13 03:21
now resolved in version @2.1.7 . 
update package and give me feedback .

**Comment by MinaSamir11** [comment] 2021-01-15 22:52
is problem still existing ?

**Comment by perrosnk** [comment] 2021-01-15 23:15
@MinaSamir11 I haven't tested yet. I will let you know

**Comment by kperreau** [comment] 2021-02-03 15:15
Look like good for me, no more crash, i'll keep you in touch if any new problems.

Thank's.

**Closed** 2021-03-23 10:54 UTC
